### ISSUE TITLE
HanldeSystemMessages Method Screwy after integrating LUIS

### ISSUE THREAD

**Issue by neilpeterson** [neilpeterson/redmond-dining-bot#1]
How can a system message be differentiated from a user initiated message, and can I filter for this on the post method?

**Comment by jongeller** [comment]
Is this a message coming from the bot or from LUIS?

**Comment by neilpeterson** [comment]
The bot, after some quick scan it looks like the HandleSystemMessages method is not being called. I must have inadvertently removed something. Will come back around to fix.

**Comment by neilpeterson** [comment]
resolved after v3 upgrade.
