### ISSUE TITLE
Convert menu logic to Linq Query

### ISSUE THREAD

**Issue by neilpeterson** [neilpeterson/redmond-dining-bot#16]
Current logic consist of nested conditions, I am assuming this would be optimized with a Linq query.

``` none
foreach (var item in list)
{
    menu += "**" + item.Name + "** \n\n";

    foreach (var item2 in item.CafeItems)
    {
        foreach (var item3 in item2.WeekDays)
        {
            if (item3 == "FRI")
            {
                menu += "- " + item2.Name + "\n\n";
            }
         }
    }
}
```

**Comment by jongeller** [comment]
@neilpeterson take a look at my branch. I added commit efb256a which incorporates the linq rewrite and for fun added a immediate response when a user sends a message.

``` C#
list.ForEach(i => {
                    menu.AppendFormat("**{0}**{1}{1}", i.Name, Environment.NewLine);
                    i.CafeItems.ToList().ForEach(ci => 
                                        menu.AppendFormat("- {0}{1}{1}", ci.Name,
                                        Environment.NewLine));
                });
```

I didn't know what words to use to trigger LUIS to provide access to the list-menu option. So I could not test the code. 

**Can you give me some sample phrases so I can test each case?**

**Comment by neilpeterson** [comment]
These three should work.
- What can I eat in cafe 16? (find-menu)
- Where can I eat pizza? - (find-food)
- Show me all dining options. - (list-all-cafe)

**Comment by jongeller** [comment]
thanks!
This is now merged to master and closed.
