### ISSUE TITLE
Add date offset

### ISSUE THREAD

**Issue by neilpeterson** [neilpeterson/redmond-dining-bot#22]
For instance:

What will the building 16 menu be on Friday.
What can I eat in building 4 tomorrow.

**Comment by jongeller** [comment]
@neilpeterson 
So, this seems to be LUIS focused. I'm happy to help once we can get the returned LUIS object to contain this data.

**Comment by neilpeterson** [comment]
Yep, will just need to add some items to LUIS. I can work on this Friday. I also sent you the LUIS details if you want to jump in.

**Comment by neilpeterson** [comment]
I started working on this, however have hit a small snag. I will sync with you on it today.
