### ISSUE TITLE
Add conversation / dialog when cafe is not found

### ISSUE THREAD

**Issue by neilpeterson** [neilpeterson/redmond-dining-bot#27]
Where a cafe is not found, return a list of all cafe's and ask if the consumer would like to see the menu for any of them.

Workflow:

``` none
user - What can I eat in building 9999?
bot - I'm sorry, I cannot find a menu for building 9999
bot - here is a list of all cafes, would you like to see the menu for any of them
user - yes, let me see cafe 16
bot - returns menu
```

See this doc for code reference - https://docs.botframework.com/en-us/csharp/builder/sdkreference/dialogs.html

**Comment by medhavinv** [comment]
started looking into this. running in to issues with PromptDialog.Confirm - it doesn't seem to distinguish between yes/no. 

Will look in to this further later.

**Comment by medhavinv** [comment]
Another way to hack around this would be to create global variables to hold the state of the bot. Let LUIS determine the yes/no response and we can handle this in code based on the state of the bot. 

This is going to be very messy and may not scale. However, it may suffice if we only plan to maintain states for this feature and the shuttle booking.

**Comment by neilpeterson** [comment]
@medhavinv thanks, whatever makes sense. Let's keep playing around with it, see what we can come up with.

**Comment by neilpeterson** [comment]
I also had a go at this, I've pulled up a branch with my solution. I do not think it is spot on / super ideal but works. We may want to sync up and discuss how to proceed with so many 'experimental branches'.

One option that comes to mind is to not merge the more experimental items into master, and instead colab on pulling these in under the tent next week.

**Comment by neilpeterson** [comment]
Here is a quick demo.

![cafenotfounddialog](https://cloud.githubusercontent.com/assets/7844635/17011770/dfd38f48-4ec5-11e6-942d-9e1473713a50.png)

**Comment by medhavinv** [comment]
Yea, that is similar to what I have. Perhaps we can also make the user respond "yes" just once? 

I also experimented with a flag for context so the bot knows if the yes/no corresponds to the see all café list or confirm shuttle schedule. I created a yes/no intent with no entities in Luis as well so the bot can understand things like "yeah, that's right", "no, wrong!" etc. 

About merging, I think your change and mine can be easily merged.

**Comment by neilpeterson** [comment]
Agrees on user responding yes only once. Using the dialog template provided in the Bot Framework documentation, I was unable to figure out how to trim it down. But this was my first swag. 

There are other issue here, like if the user was to just randomly type yes, the conversation would get sucked into the dialog. I think some sort of contextual flag as you've suggested makes sense.

Looking forward to comparing notes / collaborating with you and landing on a good project wide solution.

**Comment by medhavinv** [comment]
Another thing that's still an open issue to me is how to pass arguments in to the _IDialog_ via _IAwaitable<IMessageActivity> argument_. If we will passing a LUIS intent to the Dialog, it must be in _argument_. I have not really looked in to this yet though, any thoughts?

**Comment by neilpeterson** [comment]
Dug into this some more. It works once, but can not be executed a second time - something is still wonky.
