### ISSUE TITLE
Optimize Performance - Roll Up Issue

### ISSUE THREAD

**Issue by neilpeterson** [neilpeterson/redmond-dining-bot#31]
This issue will note all know items that my impact performance.

**Comment by jongeller** [comment]
So, a suggestion for how to determine where the lag is occurring.

Let add debug sections. Add code that only works in debug mode, which will time how long it takes to complete each segment of code.

**Comment by medhavinv** [comment]
Did a quick investigation with stop watches on command " where can I get pizza" : 
Time elapsed at start: 00:00:00.0000019
Time elapsed after LUIS: 00:00:00.5050569
Time elapsed after HTTP client init and auth: 00:00:01.8067938
Time elapsed after get call and JsonConvert: 00:00:02.8431090
Time elapsed after find food: 00:00:02.8444657

It seems like moving the lines 
`// Get authentication token from authentication.cs
            Authentication auth = new Authentication();
            string authtoken = await auth.GetAuthHeader();`

`// Get JSON – List of all Cafe serving the requested item
            HttpClient httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", authtoken);`

out of each method's call and initializing them once on boot should save us 1.3 seconds.

**Comment by medhavinv** [comment]
tried it and committed on my personal branch call-shuttle-clean-up (3ea6a168f90c9f14e252eabc9bea0babed08a5ae). 

First time asking takes about as long as before

Second time asking what can I eat in café 16:
Time elapsed at start: 00:00:00.0000003
Time elapsed after LUIS: 00:00:00.2493921
Time elapsed after REST call and JsonConvert: 00:00:00.6615343
Time elapsed after find menu: 00:00:01.1103064

followed by where can I eat pizza:
Time elapsed at start: 00:00:00.0000003
Time elapsed after LUIS: 00:00:00.3172270
Time elapsed after REST call and JsonConvert: 00:00:01.1860546
Time elapsed after find food: 00:00:01.1868802

The first time takes equally as long as before (2 seconds). I did this by hacking around the constructor for MessagesController. I'm not sure how constructors in C# works so i'll need your feedback once I submit the pull request. It's a bit hacky and I want an extra pair of eyes to look at it :)

**Comment by jongeller** [comment]
I can take a look today :) @medhavinv
