### ISSUE TITLE
Add ability to book a shuttle (demo only)

### ISSUE THREAD

**Issue by medhavinv** [neilpeterson/redmond-dining-bot#32]
Add the ability to book and cancel a shuttle. The user must be able to ask the bot to schedule a shuttle from the user's location and schedule shuttles for their friends:
1. \- bot asks user for number of people. 
2. \- bot asks user for pickup building
3. \- bot asks user for drop off building or infers it from the conversation (pending Dialogue) 
4. \- bot asks user for number of people for this destination.
   4.1 - bot checks for fixed route shuttle and denies booking as necessary.
5. - if there are remaining people (>0), bot loops to 2.
6. -user requests shuttle cancelation. If bot created multiple trips, it asks which trip.

Demo scope: show that bot is aware of context, no need to actually book a shuttle/cancel, just confirmation statement from bot may suffice.

See POST: /api/Transportation/v2/book/pickup/{pickup}/dropoff/{dropoff}/ridercount/{ridercount}

**Comment by medhavinv** [comment]
checked in ability to book shuttle.

**Comment by medhavinv** [comment]
Closed with #47.

**Comment by medhavinv** [comment]
Closed with #47.

**Comment by jongeller** [comment]
@medhavinv is this tested? (if so, so cool!)

**Comment by medhavinv** [comment]
@jongeller  Only for shuttle booking though. See the screenshot in the PR. However, it doesn't sustain a conversation like what's outlined in the Issue item :( Today it's like:

User shows intent to book shuttle
Bot confirms shuttle schedule
User replies with yes/no (or something with that intent)
Bot sends confirmation message. 

It also doesn't call the API yet since we won't be able to do it at the hackathon/science fair
