### ISSUE TITLE
Keep a readme.md of sample user messages LUIS will understand

### ISSUE THREAD

**Issue by jongeller** [neilpeterson/redmond-dining-bot#41]
@neilpeterson @medhavinv 
Could we create a MD file that contains sample messages that will trigger each path in luis?
Tracking in the bugs is good, but it will be hard to find #38 after a while.

**Comment by neilpeterson** [comment]
Yeah, we can add these to the readme.md at project root.

**Comment by neilpeterson** [comment]
Done, feel free to update at will.
