### ISSUE TITLE
Make bot response more human

### ISSUE THREAD

**Issue by medhavinv** [neilpeterson/redmond-dining-bot#58]
Right now, the bot just lists all cafes/places to eat. It should sound more human. 

For find-food:
Add phrases like "Here's where you can find pizza" when successful and "Sorry, I can't find a cafeteria that offers pizza." when fail.

For find-menu:
Add phrases like "Here's what you can eat:" when successful and "Sorry, I can't find cafe 21312" when fail.

**Comment by neilpeterson** [comment]
Merged thanks.
