### ISSUE TITLE
Formatting on "Show all dining options"

### ISSUE THREAD

**Issue by neilpeterson** [neilpeterson/redmond-dining-bot#80]
![7-26-2016 11-07-32 pm](https://cloud.githubusercontent.com/assets/7844635/17165532/e1f3cefe-5385-11e6-8bad-b2b2df3def1a.png)

**Comment by medhavinv** [comment]
Adding an extra new line should do the trick.

**Comment by medhavinv** [comment]
fixed with PR #84
